manifestVersion: '1.0'
issuer: nexus-dev
issuedAt: '2026-05-25T17:33:34.917Z'
signature: a8x1ovcSIzbKlgd3sa-rw_eAintjrODBVgpnhOn0t_jpWAfuo2AGsrTse8W6f_n9i5QbwMP17LlKZwc42fXpBA
body:
  endpoints:
    - endpointId: local-ollama
      tier: on_prem_general
      url: http://localhost:11434/api/chat
      adapterId: ollama-chat-v1
      modelName: llama3.2
      timeoutMs: 120000
      auth:
        kind: none
      enabled: false
    - endpointId: anthropic-claude
      tier: frontier_general
      url: https://api.anthropic.com/v1/messages
      adapterId: anthropic-messages-v1
      modelName: claude-sonnet-4-20250514
      auth:
        kind: api_key
        secretRef: file:ANTHROPIC_API_KEY
        headerName: x-api-key
      adapterConfig:
        max_tokens: 4096
      enabled: false
    - endpointId: openai-gpt
      tier: frontier_general
      url: https://api.openai.com/v1/chat/completions
      adapterId: openai-chat-v1
      modelName: gpt-4o
      auth:
        kind: bearer
        secretRef: file:OPENAI_API_KEY
        headerName: Authorization
        prefix: 'Bearer '
      enabled: true
    - endpointId: ollama-blackmac
      url: http://192.168.1.59:11434/api/chat
      adapterId: ollama-chat-v1
      modelName: qwen3.5:0.8b
      tier: on_prem_general
      timeoutMs: 120000
      enabled: false
      auth:
        kind: none
    - endpointId: ollama-jameshp
      url: http://10.31.1.105:11434/api/chat
      adapterId: ollama-chat-v1
      modelName: granite3-dense:latest
      tier: on_prem_general
      timeoutMs: 120000
      enabled: true
      auth:
        kind: none
    - endpointId: ollama-jameshp2
      url: http://10.31.1.112:11434/api/chat
      adapterId: ollama-chat-v1
      modelName: gemma2:2b
      tier: on_prem_sensitive
      timeoutMs: 120000
      enabled: true
      auth:
        kind: none
    - endpointId: ollama-jamesImac
      url: http://10.31.1.108:11434/api/chat
      adapterId: ollama-chat-v1
      modelName: qwen2.5:1.5b
      tier: on_prem_general
      timeoutMs: 120000
      enabled: true
      auth:
        kind: none
