manifestVersion: '1.0'
issuer: nexus-dev
issuedAt: '2026-05-10T23:32:10.365Z'
signature: btogkDZtsPN0muBf620mHrSbd93-HCZBKRwLoj33C8D3rW1SUuCXtvHFLn-qlTG-cy7ppLp6xkmo-MSTzoHnCQ
body:
  providers:
    - providerId: ria
      providerType: reference_adapter
      configuration: {}
      enabled: true
