manifestVersion: '1.0'
issuer: nexus-dev
issuedAt: '2026-05-10T23:32:07.833Z'
signature: _TNpvT64fQMY2lKC4eHFgV1Z9vvNPX5uGAsI3BrjmYUVPp4drSERjgpqThIxNXqSmZfCCS2GEqv0ijWCjHxyDw
body:
  channels:
    - channelId: cli
      channelType: cli
      configuration: {}
      enabled: true
